version: '5.0.{build}'
image: Visual Studio 2017
clone_depth: 1
deploy: off
branches:
  only:
  - master
init:
  - cmd: git config --global core.autocrlf true
build_script:
  - cmd: dotnet --version
  - cmd: dotnet restore -v q
  - cmd: dotnet build -c Release -f net45 "src\StringDB\StringDB.csproj"
  - cmd: dotnet build -c Release -f netstandard2.0 "src\StringDB\StringDB.csproj"
artifacts:
 - path: 'src\StringDB\bin\Release\netstandard2.0\'
   name: StringDB_netstandard2.0
 - path: 'src\StringDB\bin\Release\net45\'
   name: StringDB_net45