version: '0.0.{build}'
image: Visual Studio 2017
clone_depth: 1
deploy: off
branches:
  only:
  - master
init:
  - cmd: git config --global core.autocrlf true
build_script:
  - cmd: dotnet --version
  - cmd: dotnet restore
  - cmd: dotnet build "C:\projects\stringdb\StringDB\StringDB.csproj"
artifacts:
 - path: 'bin\Debug\netcoreapp2.0\publish'
   name: StringDB