site_name: StringDB
site_author: SirJosh3917
repo_url: https://github.com/SirJosh3917/StringDB
edit_uri: "blob/gh-pages/mkdocs-src/docs/"
nav:
    - Home: "index.md"
    - Database Documentation:
        - "IDatabase Interface": "dbs/IDatabase.md"
        - "Base Database": "dbs/BaseDatabase.md"
        - "Cache Database": "dbs/CacheDatabase.md"
        - "Memory Database": "dbs/MemoryDatabase.md"
        - "Thread Lock Database": "dbs/ThreadLockDatabase.md"
        - IODatabase:
            - "IO Database": "dbs/IODatabase/IODatabase.md"
            - Database IO Device:
                - "IDatabaseIODevice Interface": "dbs/IODatabase/DatabaseIODevice/IDatabaseIODevice.md"
                - "Database IO Device": "dbs/IODatabase/DatabaseIODevice/DatabaseIODevice.md"
                - Database IO Devices:
                    - "StoneVault IO Device": "dbs/IODatabase/DatabaseIODevice/DatabaseIODevices/StoneVaultIODevice.md"
                - Lowlevel Database IO Devices:
                    - "ILowlevelDatabaseIODevice Interface": "dbs/IODatabase/DatabaseIODevice/LowlevelDatabaseIODevices/ILowlevelDatabaseIODevice.md"
                    - "StringDB5_0_0LowlevelDatabaseIODevice": "dbs/IODatabase/DatabaseIODevice/LowlevelDatabaseIODevices/StringDB5_0_0LowlevelDatabaseIODevice.md"
                    - "StringDB10_0_0LowlevelDatabaseIODevice": "dbs/IODatabase/DatabaseIODevice/LowlevelDatabaseIODevices/StringDB10_0_0LowlevelDatabaseIODevice.md"
        - Transform Database:
            - "Transform Database": "dbs/TransformDatabase/TransformDatabase.md"
theme: 